application: code-ben2o
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /
  static_files: index.html
  upload: index.html
  
- url: /index.html
  static_files: index.html
  upload: index.html

- url: /static
  static_dir: static
  expiration: 1m

- url: /.*
  script: backend.application
    
libraries:
- name: webapp2
  version: "2.5.1"
  
 

